import { IndustryPreset } from './types';
import { INDUSTRY_MEDIA_MAP } from '@/lib/industry-media';

export const barbershopPreset: IndustryPreset = {
  id: 'barbershop',
  name: 'מספרת גברים ופיסול זקן',
  categoryName: 'מספרות גברים',
  icon: '💈',
  badge: 'פרימיום Barber Hub',
  description: 'מראה פחם מט יוקרתי, דירוגים כירורגיים, סליידר לפני/אחרי ואווירת גברים פרימיום.',
  themeColor: '#C9A84C', // Gold Obsidian
  bgTheme: 'dark-obsidian',
  heroStyle: 'hub-monogram',
  servicesStyle: 'split-gallery',
  galleryStyle: 'before-after-slider',
  heroImages: INDUSTRY_MEDIA_MAP.barber.heroImages,
  galleryImages: INDUSTRY_MEDIA_MAP.barber.galleryPhotos.map((p) => p.src),
  avatarUrl: INDUSTRY_MEDIA_MAP.barber.avatarUrl,
  showBeforeAfter: true,
  showBio: true,
  showBranches: true,
  borderRadius: 'modern-rounded',
  fontStyle: 'urban-bold',
  shopName: 'המספרה של דביר',
  ownerName: 'דביר',
  slogan: 'עיצוב שיער גברים, פיידים מדויקים ופיסול זקן ברמה הגבוהה ביותר בישראל',
  announcement: '🌟 קביעת תורים מהירה אונליין לכל הסניפים 24/7 – שריינו מקום מראש!',
  sectionsOrder: ['hero', 'announcement', 'trust-badges', 'services', 'gallery', 'bio', 'policies', 'branches', 'reviews', 'faqs'],
  transformations: [
    {
      id: '1',
      title: 'סקין פייד קלאסי ועיצוב קווי מתאר',
      category: 'תספורת פרימיום',
      description: 'מעבר משיער פרוע לפייד מדויק עם קווי מתאר חדים וטקסטורה עליונה.',
      beforeGradient: 'from-stone-900 via-stone-800 to-zinc-900',
      afterGradient: 'from-amber-900 via-amber-800 to-yellow-700',
    },
    {
      id: '2',
      title: 'פיסול זקן מלא + דירוג לחיים',
      category: 'עיצוב זקן',
      description: 'יישור סימטרי מדויק של קו הלחיים והצוואר, שמן הזנה ועיצוב עם תער חם.',
      beforeGradient: 'from-zinc-900 via-neutral-900 to-stone-900',
      afterGradient: 'from-amber-950 via-amber-900 to-amber-700',
    },
    {
      id: '3',
      title: 'פרנץ\' קרופ מודרני וטקסטורה עשירה',
      category: 'סגנון מודרני',
      description: 'מראה צעיר, רענן וקל לעיצוב יומיומי עם חימר מט פרימיום.',
      beforeGradient: 'from-neutral-900 via-zinc-800 to-stone-900',
      afterGradient: 'from-yellow-950 via-amber-800 to-yellow-600',
    },
  ],
  trustBadges: [
    'דירוג 5.0 כוכבים (420+ ביקורות Google)',
    '10+ שנות ותק וניסיון מקצועי',
    'חניה צמודה ונוחה במקום',
    'אספרסו וכיבוד פרימיום חינם',
    'תשלום נוח ב-Bit, Apple Pay ואשראי',
  ],
  services: [
    { id: 'srv-1', name: 'תספורת גברים פרימיום & דירוג', price: 80, duration: 30, description: 'תספורת מדויקת לפי מבנה הפנים, שטיפה וחפיפה ועיצוב עם ווקס פרימיום' },
    { id: 'srv-2', name: 'פיסול ועיצוב זקן Master', price: 40, duration: 20, description: 'קווים חדים בתער יפני, שמנים מזינים ומגבת חמה' },
    { id: 'srv-3', name: 'חבילת VIP משולבת (שיער + זקן)', price: 110, duration: 45, description: 'החבילה המובילה: תספורת מלאה, פיסול זקן ומסיכת פנים מרעננת' },
    { id: 'srv-4', name: 'תספורת ילדים ונוער (עד גיל 13)', price: 70, duration: 30, description: 'יחס אישי, סבלנות ודירוג אופנתי ומדויק' },
  ],
  faqs: [
    { id: 'faq-1', question: 'איך מתבצע ביטול או שינוי מועד התור?', answer: 'ניתן לבטל או לשנות את מועד התור בקלות דרך כפתור "התורים שלי" באתר עד שעתיים לפני המועד שנקבע.' },
    { id: 'faq-2', question: 'האם יש חניה מסודרת ליד המספרה?', answer: 'כן, בסניפינו ישנה חניה חינם ובשפע ממש בצמוד לכניסה.' },
    { id: 'faq-3', question: 'באילו אמצעי תשלום ניתן לשלם?', answer: 'אנו מכבדים כרטיסי אשראי, מזומן, Bit ו-Apple Pay.' },
  ],
  policies: {
    cancellationNotice: 'ביטול או שינוי תור ללא עלות עד שעתיים לפני המועד',
    arrivalTime: 'נא להגיע כ-5 דקות לפני שעת התור',
    paymentMethods: 'תשלום באשראי, Bit, Apple Pay או מזומן',
    customNote: 'במקרה של איחור מעל 10 דקות, יש לעדכן אותנו מראש בוואטסאפ',
  },
};
