import { IndustryPreset } from './types';
import { INDUSTRY_MEDIA_MAP } from '@/lib/industry-media';

export const cosmeticsPreset: IndustryPreset = {
  id: 'cosmetics-aesthetician',
  name: 'קוסמטיקה פרא-רפואית ואסתטיקה',
  categoryName: 'קוסמטיקה ועור',
  icon: '🌸',
  badge: 'P.M.E Clinical Skincare & Aesthetics',
  description: 'אווירת Lavender Mist יוקרתית, אבחון עור קליני, טיפולי אקנה ופיגמנטציה, וסליידר תוצאות לפני/אחרי.',
  themeColor: '#EC4899', // Rose Velvet / Blush
  bgTheme: 'lavender-mist',
  heroStyle: 'split-cinema',
  servicesStyle: 'cards-grid',
  galleryStyle: 'before-after-slider',
  heroImages: INDUSTRY_MEDIA_MAP.cosmetics_aesthetician.heroImages,
  galleryImages: INDUSTRY_MEDIA_MAP.cosmetics_aesthetician.galleryPhotos.map((p) => p.src),
  avatarUrl: INDUSTRY_MEDIA_MAP.cosmetics_aesthetician.avatarUrl,
  showBeforeAfter: true,
  showBio: true,
  showBranches: false,
  borderRadius: 'classic-soft',
  fontStyle: 'luxury-serif',
  typographyMood: 'luxury-serif',
  shopName: 'קליניקת Glow & Skin | קוסמטיקה פרא-רפואית',
  ownerName: 'שירן כהן (P.M.E)',
  slogan: 'קוסמטיקה פרא-רפואית מתקדמת, אבחון עור קליני, שיקום אקנה והבהרת פיגמנטציה',
  announcement: '✨ אבחון עור קליני והתאמת שגרת טיפוח אישית – שרייני תור אונליין 24/7!',
  sectionsOrder: ['announcement', 'hero', 'trust-badges', 'services', 'gallery', 'bio', 'policies', 'reviews', 'faqs'],
  transformations: [
    {
      id: 'c1',
      title: 'שיקום עור אקנאי ואיזון בלוטות שומן',
      category: 'טיפול אקנה פרא-רפואי',
      description: 'תהליך ריפוי דלקות פעילות והאחדת מרקם העור לאחר 4 מפגשים קליניים.',
      beforeGradient: 'from-stone-900 via-rose-950 to-stone-900',
      afterGradient: 'from-rose-900 via-pink-800 to-rose-700',
    },
    {
      id: 'c2',
      title: 'הבהרת כתמי פיגמנטציה ופוסט-אקנה',
      category: 'פילינג חומצות משולב',
      description: 'פילינג מותאם אישית בשילוב חומצות אלפא-הידרוקסי להבהרה אחידה וזוהרת.',
      beforeGradient: 'from-zinc-900 via-neutral-900 to-stone-900',
      afterGradient: 'from-fuchsia-950 via-pink-900 to-rose-700',
    },
    {
      id: 'c3',
      title: 'חידוש והצערת עור הפנים (Glow Rejuvenation)',
      category: 'אנטי-אייג׳ינג & מזותרפיה',
      description: 'החדרת פפטידים וחומצה היאלורונית למיצוק העור וטשטוש קמטוטים.',
      beforeGradient: 'from-neutral-900 via-zinc-800 to-stone-900',
      afterGradient: 'from-pink-950 via-rose-900 to-purple-800',
    },
  ],
  trustBadges: [
    'הסמכה פרא-רפואית בכירה P.M.E',
    'חומרים פעילים באישור משרד הבריאות',
    'מכשור טכנולוגי מתקדם לחידוש העור',
    'סטריליזציה רפואית באוטוקלאב (Autoclave)',
    'דירוג 5.0★ (340+ מטופלות מרוצות)',
  ],
  services: [
    { id: 'srv-cos-1', name: 'טיפול פנים עמוק & אבחון עור קליני', price: 350, duration: 60, description: 'ניקוי עמוק, ניקוז קומדונים, החדרת לחויות עמוקה והרגעת העור בחומרים פעילים' },
    { id: 'srv-cos-2', name: 'טיפול שיקום אקנה ואיזון סבום', price: 420, duration: 75, description: 'פרוטוקול טיפולי קליני להפחתת דלקות, ויסות בלוטות החלב ושיקום מחסום העור' },
    { id: 'srv-cos-3', name: 'הבהרת פיגמנטציה & פילינג חומצות', price: 480, duration: 60, description: 'קילוף מבוקר של שכבות העור העליונות, פירוק מלנין והבהרת כתמי שמש וגיל' },
    { id: 'srv-cos-4', name: 'אנטי-אייג׳ינג פרימיום & מזותרפיה', price: 650, duration: 90, description: 'מיקרונידלינג מתקדם להמרצת קולגן ואלסטין, מיצוק וטשטוש קמטוטים' },
    { id: 'srv-cos-5', name: 'הרמת ריסים והזנת קרטין', price: 220, duration: 45, description: 'הדגשה והרמה טבעית של הריסים עם סרום קרטין מזין ל-8 שבועות' },
    { id: 'srv-cos-6', name: 'עיצוב ושיקום גבות בשיטת השערה', price: 120, duration: 30, description: 'פיסול והתאמה למבנה הפנים, צביעה בחומרים צמחיים ושיקום צמיחה' },
  ],
  faqs: [
    { id: 'faq-cos-1', question: 'מה כולל הטיפול הראשון בקליניקה?', answer: 'כל טיפול ראשון נפתח באבחון קליני מעמיק של סוג העור, תשאול רפואי ובניית תוכנית טיפול אישית ושגרת בית.' },
    { id: 'faq-cos-2', question: 'מתי רואים תוצאות בטיפולי אקנה או פיגמנטציה?', answer: 'שיפור ברמת הדלקת והברק נראה כבר מהטיפול הראשון. שיקום יסודי מתרחש בהדרגה לאורך סדרת טיפולים.' },
    { id: 'faq-cos-3', question: 'האם הטיפולים מתאימים בהריון או הנקה?', answer: 'בהחלט! אנו מתאימים פרוטוקול טיפולי בטוח ללא חומצות אגרסיביות או רטינול.' },
    { id: 'faq-cos-4', question: 'האם הטיפול כואב?', answer: 'הטיפולים מבוצעים בעדינות מרבית, עם טכניקות הרגעה והכנת העור למניעת כאב או אי נוחות.' },
  ],
  policies: {
    cancellationNotice: 'ביטול או שינוי תור עד 24 שעות מראש ללא עלות',
    arrivalTime: 'נא להגיע כ-5 דקות לפני הזמן ללא איפור',
    paymentMethods: 'Bit, Apple Pay, אשראי והעברה בנקאית',
    customNote: 'חובה לדווח על נטילת רואקוטן או הריון. יש להימנע מחשיפה לשמש 48 שעות לאחר הטיפול',
  },
};
