import { IndustryPreset } from './types';
import { INDUSTRY_MEDIA_MAP } from '@/lib/industry-media';

export const nailsBeautyPreset: IndustryPreset = {
  id: 'nails-beauty',
  name: 'סטודיו למניקור, לק ג׳ל ומבנה אנטומי',
  categoryName: 'ציפורניים ומניקור',
  icon: '💅',
  badge: 'Russian Manicure & Apex Studio',
  description: 'מניקור משולב ומבנה אנטומי מדויק, חיזוק בסיס רבר, גלריית נייל ארט עשירה, וחיטוי באוטוקלאב רפואי.',
  themeColor: '#8B5CF6', // Royal Lilac & Lavender
  bgTheme: 'lavender-mist',
  heroStyle: 'split-cinema',
  servicesStyle: 'cards-grid',
  galleryStyle: 'instagram-masonry',
  heroImages: INDUSTRY_MEDIA_MAP.beauty_salon.heroImages,
  galleryImages: INDUSTRY_MEDIA_MAP.beauty_salon.galleryPhotos.map((p) => p.src),
  avatarUrl: INDUSTRY_MEDIA_MAP.beauty_salon.avatarUrl,
  showBeforeAfter: true,
  showBio: true,
  showBranches: false,
  borderRadius: 'classic-soft',
  fontStyle: 'luxury-serif',
  typographyMood: 'luxury-serif',
  shopName: 'סטודיו מיה | לק ג׳ל & מבנה אנטומי',
  ownerName: 'מיה',
  slogan: 'מניקור רוסי משולב, מבנה אנטומי עמיד ל-4 שבועות ונייל ארט פרימיום',
  announcement: '🌸 פתיחת יומן תורים לחודש הקרוב – שרייני תור למבנה אנטומי אונליין!',
  sectionsOrder: ['announcement', 'hero', 'trust-badges', 'gallery', 'services', 'bio', 'policies', 'reviews', 'faqs'],
  transformations: [
    {
      id: 'n1',
      title: 'מניקור רוסי נקי ומריחה צמודה לעור',
      category: 'מניקור משולב & לק ג׳ל',
      description: 'ניקוי קוטיקולה מושלם ללא פציעות ומריחת גוון ניוד מתחת לקוטיקולה.',
      beforeGradient: 'from-stone-900 via-purple-950 to-stone-900',
      afterGradient: 'from-purple-900 via-fuchsia-800 to-pink-700',
    },
    {
      id: 'n2',
      title: 'חיזוק ציפורן דקה במבנה אנטומי עמיד',
      category: 'Apex Rubber Base',
      description: 'יצירת קשת אנטומית יציבה ועמידה במיוחד המונעת סדקים ושבירות למשך 4 שבועות.',
      beforeGradient: 'from-zinc-900 via-neutral-900 to-stone-900',
      afterGradient: 'from-pink-950 via-purple-900 to-indigo-800',
    },
    {
      id: 'n3',
      title: 'עיצוב פרנץ׳ ואפקט כרום מזוגג (Glazed Chrome)',
      category: 'נייל ארט פרימיום',
      description: 'מראה מואר, נקי וטרנדי בהשראת היילי ביבר בגימור מבריק כראי.',
      beforeGradient: 'from-neutral-900 via-zinc-800 to-stone-900',
      afterGradient: 'from-fuchsia-950 via-pink-900 to-rose-700',
    },
  ],
  trustBadges: [
    'סטריליזציה ברמה רפואית (Autoclave)',
    'שקיות עיקור אישיות שנפתחות מולך',
    'חומרי פרימיום היפואלרגניים בלבד',
    'אחריות מלאה ל-5 ימים על כל טיפול',
    'דירוג 5.0★ (280+ לקוחות מרוצות)',
  ],
  services: [
    { id: 'srv-101', name: 'מניקור משולב & לק ג׳ל במבנה אנטומי', price: 160, duration: 60, description: 'ניקוי קוטיקולה יסודי (מניקור קומבי), חיזוק בסיס רבר גומי ומריחה מדויקת וצמודה לעור' },
    { id: 'srv-102', name: 'הארכת ציפורניים בפוליג׳ל / ג׳ל טיפס (סט חדש)', price: 260, duration: 90, description: 'בנייה חזקה, קלה וטבעית למראה ציפורניים ארוכות ומעוצבות במיוחד' },
    { id: 'srv-103', name: 'מילוי וחידוש מבנה אנטומי / בנייה קיימת', price: 170, duration: 60, description: 'הסרה מבוקרת, ניקוי מניקור רוסי מחדש, יישור מבנה אנטומי ומריחת לק חדש' },
    { id: 'srv-104', name: 'פדיקור טיפולי / רפואי משולב ומפנק', price: 190, duration: 50, description: 'הסרת עור יבש וסדוק, גזירה נכונה למניעת ציפורן חודרנית, עיסוי קרם הזנה ומריחה' },
    { id: 'srv-105', name: 'שדרוג נייל ארט: פרנץ׳ / כרום גלייזד / בייבי בומר', price: 30, duration: 15, description: 'עיצוב אומנותי מדויק על כל הציפורניים בגימור מודרני מרהיב' },
    { id: 'srv-106', name: 'הסרת לק ג׳ל ישן ממכון אחר', price: 30, duration: 20, description: 'הסרה עדינה ובטוחה בשיוף מבוקר ללא פגיעה בלוחית הציפורן הטבעית' },
    { id: 'srv-107', name: 'השלמת / תיקון ציפורן שבורה', price: 20, duration: 15, description: 'איחוי ותיקון ציפורן שבורה או סדוקה בחומר פוליג׳ל מחוזק' },
  ],
  faqs: [
    { id: 'faq-101', question: 'מה ההבדל בין לק ג׳ל רגיל למבנה אנטומי?', answer: 'מבנה אנטומי כולל יישור שכבת הבסיס ויצירת קשת Apex במרכז הציפורן, המעניקה עמידות מקסימלית ומגנה על הציפורן הטבעית משבירה.' },
    { id: 'faq-102', question: 'כמה זמן מחזיק מבנה אנטומי?', answer: 'מבנה אנטומי מחזיק בין 3 ל-4 שבועות בעמידות מלאה, ברק מושלם וללא קילופים.' },
    { id: 'faq-103', question: 'האם המכשור עובר חיטוי וסטריליזציה?', answer: 'בוודאי! כל כלי העבודה עוברים חיטוי יסודי באוטוקלאב רפואי ונפתחים משקית סטרילית עם אינדיקטור מול עיני הלקוחה.' },
    { id: 'faq-104', question: 'מה עושים אם מגיעים עם לק ממכון אחר?', answer: 'יש לסמן שירות "הסרת לק ג׳ל ממכון אחר" בעת קביעת התור כדי שנוכל לשריין את הזמן הנדרש להסרה בטוחה.' },
  ],
  policies: {
    cancellationNotice: 'ביטול או שינוי תור עד 24 שעות מראש ללא עלות',
    arrivalTime: 'נא להגיע בזמן מדויק וללא ליווי לטובת שקט, סטריליות ופרטיות',
    paymentMethods: 'Bit, PayBox, אשראי והעברה בנקאית',
    customNote: 'מגיעה עם לק ג׳ל קיים ממכון אחר? אנא סמני מראש תוספת הסרה',
  },
};
