import { BusinessConfig } from '@/types/business';

export const DVIR_FLAGSHIP_CONFIG: BusinessConfig = {
  id: 'biz-dvir',
  name: 'המספרה של דביר',
  slug: 'dvir',
  ownerName: 'דביר',
  phone: '052-123-4567',
  city: 'אריאל & רחובות',
  slogan: 'עיצוב שיער גברים, פיידים מדויקים ופיסול זקן ברמה הגבוהה ביותר בישראל',
  announcement: '🌟 קביעת תורים מהירה אונליין לכל הסניפים 24/7 – שריינו מראש!',
  themeColor: '#C9A84C',
  branchesCount: 2,
  status: 'active',
  plan: 'enterprise',
  experienceYears: 7,
  instagramHandle: '@dvir_barbershop',
  services: [
    {
      id: '1',
      name: 'תספורת גברים פרימיום',
      price: 80,
      duration: 30,
      description: 'כולל חפיפה מפנקת, דירוג Fade מדויק ועיצוב עם ווקס/חימר יוקרתי',
      popular: true,
    },
    {
      id: '2',
      name: 'עיצוב ופיסול זקן Master',
      price: 40,
      duration: 20,
      description: 'תיחום קווים בתער יפני, ריכוך בשמנים מזינים ומגבת חמה',
      popular: false,
    },
    {
      id: '3',
      name: 'חבילת VIP משולבת (תספורת + זקן)',
      price: 110,
      duration: 45,
      description: 'החוויה המושלמת לגבר: תספורת Fade, פיסול זקן, טיפול מגבת חמה וחפיפה',
      popular: true,
    },
    {
      id: '4',
      name: 'תספורת ילדים ונוער',
      price: 70,
      duration: 30,
      description: 'תספורת אופנתית וסבלנית לילדים ונוער באווירה צעירה ונעימה',
      popular: false,
    },
  ],
  branches: [
    {
      id: 'ariel',
      name: 'סניף אריאל – אוניברסיטת אריאל',
      address: 'קמפוס אוניברסיטת אריאל (מרכז הסטודנט)',
      phone: '052-123-4567',
      hours: 'א׳-ה׳: 09:00-20:00 | ו׳: 08:30-14:00',
      wazeLink: 'https://waze.com/ul?q=Ariel%20University',
      googleMapsLink: 'https://maps.google.com/?q=Ariel+University',
    },
    {
      id: 'rehovot',
      name: 'סניף רחובות – מרכז העיר',
      address: 'הרצל 180, רחובות (ליד מכון ויצמן)',
      phone: '052-123-4567',
      hours: 'א׳-ה׳: 10:00-21:00 | ו׳: 08:30-14:30',
      wazeLink: 'https://waze.com/ul?q=Herzl%20180%20Rehovot',
      googleMapsLink: 'https://maps.google.com/?q=Herzl+180+Rehovot',
    },
  ],
  testimonials: [
    {
      id: 't1',
      name: 'עומר לוי',
      comment: 'הספר הכי מדויק שיש! פייד מושלם כל פעם מחדש. הממשק לקביעת תור פשוט הצלה.',
      rating: 5,
      timeAgo: 'לפני 3 ימים',
      serviceUsed: 'תספורת גברים פרימיום',
    },
    {
      id: 't2',
      name: 'יונתן כהן',
      comment: 'חבילת ה-VIP שווה כל שקל! פיסול הזקן והמגבת החמה זו חוויה של מספרה מהשורה הראשונה.',
      rating: 5,
      timeAgo: 'לפני שבוע',
      serviceUsed: 'חבילת VIP משולבת',
    },
    {
      id: 't3',
      name: 'רועי ששון',
      comment: 'שירות מעל המצופה, עמידה מדויקת בזמנים, אווירה טובה ומקצוענות שיא!',
      rating: 5,
      timeAgo: 'לפני שבועיים',
      serviceUsed: 'תספורת גברים פרימיום',
    },
  ],
  faqs: [
    {
      question: 'האם חובה לקבוע תור מראש?',
      answer: 'כן, כדי להבטיח שלא תמתינו אפילו דקה אחת, אנו עובדים במתכונת תורים מוזמנים מראש דרך המערכת.',
    },
    {
      question: 'האם ניתן לבטל או להזיז תור?',
      answer: 'בהחלט! ניתן לבטל תור בקלות דרך עמוד "איתור וניהול התורים שלי" עד שעתיים לפני מועד התור ללא עלות.',
    },
    {
      question: 'אילו אמצעי תשלום מתקבלים במספרה?',
      answer: 'אנו מקבלים מזומן, אשראי, Bit, PayBox והעברה בנקאית.',
    },
    {
      question: 'האם יש חניה צמודה בסניפים?',
      answer: 'כן, בשני הסניפים באריאל וברחובות קיימת חניה מסודרת ונגישה ללקוחותינו.',
    },
  ],
};
