export const demosSuite = {
  id: 'demos',
  title: 'Showcase Demo Sites & Booking Flows (אתרי הדגמה לכל הנישות)',
  description: 'Verifies dynamic SSR routing, industry isolation, and customer-facing booking interfaces for all 8 business verticals.',
  targets: [
    {
      name: 'Barber Hub Flagship Demo (/dvir)',
      path: '/dvir',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      contentCheck: 'דביר',
      maxLatencyMs: 3000,
    },
    {
      name: 'Beauty & Nails Niche Demo (/beauty)',
      path: '/beauty',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Spa & Massage Niche Demo (/spa)',
      path: '/spa',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Fitness & Gym Trainer Demo (/fitness)',
      path: '/fitness',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Aesthetics Clinic Demo (/clinic)',
      path: '/clinic',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Technician & Home Services Demo (/tech)',
      path: '/tech',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Tattoo & Piercing Studio Demo (/tattoo)',
      path: '/tattoo',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Customer Booking Portal (/booking)',
      path: '/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Customer Self-Management (/booking/manage)',
      path: '/booking/manage',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
  ],
};
