export const demosSuite = {
  id: 'demos',
  title: 'Showcase Demo Sites & Industry Booking Flows (אתרי הדגמה ומנועי זימון לכל הענפים)',
  description: 'Verifies dynamic SSR routing, industry isolation, on-site technician flows, salon booking, and customer self-management across all 8 business verticals.',
  targets: [
    {
      name: 'Barber Hub Flagship Demo (/dvir)',
      path: '/dvir',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      contentCheck: 'דביר',
      maxLatencyMs: 3000,
    },
    {
      name: 'Beauty & Nails Niche Demo (/beauty)',
      path: '/beauty',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Spa & Massage Niche Demo (/spa)',
      path: '/spa',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Fitness & Gym Trainer Demo (/fitness)',
      path: '/fitness',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Aesthetics Clinic Demo (/clinic)',
      path: '/clinic',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Technician & Home Services Demo (/tech)',
      path: '/tech',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Tattoo & Piercing Studio Demo (/tattoo)',
      path: '/tattoo',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Universal Booking Hub (/booking)',
      path: '/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      contentCheck: 'פורטל זימון תורים',
      maxLatencyMs: 3000,
    },
    {
      name: 'Delegated Technician Booking (/booking?slug=tech)',
      path: '/booking?slug=tech',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Direct Technician Home Visit Booking (/tech/booking)',
      path: '/tech/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      contentCheck: 'קריאת שירות',
      maxLatencyMs: 3000,
    },
    {
      name: 'Direct Barber Chair Booking (/dvir/booking)',
      path: '/dvir/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Direct Beauty & Nails Booking (/beauty/booking)',
      path: '/beauty/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Direct Spa & Massage Booking (/spa/booking)',
      path: '/spa/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Direct Fitness Trainer Booking (/fitness/booking)',
      path: '/fitness/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Direct Aesthetics Clinic Booking (/clinic/booking)',
      path: '/clinic/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Direct Tattoo Studio Booking (/tattoo/booking)',
      path: '/tattoo/booking',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
    {
      name: 'Customer Self-Management Portal (/booking/manage)',
      path: '/booking/manage',
      expectedStatus: 200,
      expectedContentType: 'text/html',
      maxLatencyMs: 3000,
    },
  ],
};
